### ISSUE TITLE
pcmanfm-qt does not search XDG_DATA_HOME for icons

### ISSUE THREAD

**Issue by majorbob** [lxde/pcmanfm-qt#99] opened 2014-10-19 14:19 UTC
Wine installs application icons to ~/.local/share/icons/hicolor.
pcmanfm-qt managing the desktop does not search the directory for icons. 
pcmanfm from LXDE has correct behaviour and searches the directory and shows desktop icons correctly.

**Comment by PCMan** [comment] 2015-01-31 16:14
We only use QIcon::fromTheme() to get the icon.
So if anything goes wrong, it's basically the bug of Qt itself.
Please report to Qt developers.

**Comment by pmattern** [comment] 2015-12-12 11:43
Superseded by lxde/lxqt#915 (strictly speaking a duplicate of this one but offering a more extensive discussion).

**Closed by pmattern** 2015-12-12 11:43 UTC
