### ISSUE TITLE
File size isn't auto-updated correctly in Detailed List view

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#514] opened 2017-06-21 15:15 UTC
If I copy a file with at least 1 mb and paste it in any folder, pcmanfm-qt informs the file size wrongly, so I need to refresh it in order to get the actual file size.

This problem extends to the cases when you're copying big files and pcmanfm-qt doesn't refresh the current file size during the copy process.

Using last Git, building for Porteus x64 distro (Slackware 14.2 based).

**Comment by tsujan** [comment] 2017-06-21 16:00
I'm aware of this issue and had fixed it for myself 2 years ago but, since my patch is also for selecting newly created files, I haven't made a PR yet (the patch for selecting newly created files was rejected 2 years ago but I can't use pcmanfm-qt without it).

I'll try to separate those patches from each other and make a PR.

**Comment by tsujan** [comment] 2017-06-21 17:18
The patch is ready but let me first check with you whether we're talking about the same thing by using an example:

When a big file is being downloaded, for example, if its downloaded part is *selected*, the statusbar info won't update the size until the folder is refreshed. The same thing happens when a huge file is pasted and its pasted part is *selected* before it's complete. Now, you didn't say anything about statusbar or selection. Could you please be more specific? How does "pcmanfm-qt inform the file size wrongly" in your case?

**Comment by fulalas** [comment] 2017-06-21 20:58
> How does "pcmanfm-qt inform the file size wrongly" in your case?

In the 'size' column when in 'Detailed List' view mode.

**Comment by tsujan** [comment] 2017-06-21 21:03
Then it's a different bug; https://github.com/lxde/pcmanfm-qt/pull/515 won't fix it.

**Comment by fulalas** [comment] 2017-06-21 21:05
I see. But can you reproduce it in your machine?

**Comment by tsujan** [comment] 2017-06-21 21:08
Confirmed a few second ago. Will look into this too.

**Comment by fulalas** [comment] 2017-06-21 21:11
Thanks, man! :)

**Comment by tsujan** [comment] 2017-06-21 21:54
If I haven't been too tired, this should be fixed by a simple change: https://github.com/lxde/libfm-qt/pull/90. The bug was there for ages and no one had noticed (including me).

I tested it but if you could compile libfm-qt, your test would be appreciated. Don't forget to restart desktop after that!

**Comment by fulalas** [comment] 2017-06-22 03:10
Perfect! I think we can close this issue. Thanks once again! :)

**Comment by fulalas** [comment] 2017-06-22 03:13
Ah! Since you're excited fixing libfm-qt, what about putting this in filesearchdialog.cpp constructor:

```
    ui->nameCaseInsensitive->setChecked(true);
    ui->contentCaseInsensitive->setChecked(true);
    ui->recursiveSearch->setChecked(true);
    ui->searchHidden->setChecked(true);
```
It's the default behavior of pcmanfm of LXDE, or at least the one shipped with Lubuntu. :+1:

**Comment by tsujan** [comment] 2017-06-22 10:33
A better approach is making that dialog remember its settings. That's in my TODO list with low priority.

**Comment by fulalas** [comment] 2017-06-22 12:44
This is a nice idea! But together with your idea I think we need to set an initial behavior that reflects a more common use.

**Comment by tsujan** [comment] 2017-06-22 12:45
I agree.

**Closed** 2017-07-05 05:52 UTC
Labels: bug
