### ISSUE TITLE
Alt-F4 and pcmanfm-qt deskop 

### ISSUE THREAD

**Issue by agaida** [lxde/pcmanfm-qt#194] opened 2015-07-12 12:04 UTC
the pcmanfm-qt instance who paint the desktop should not be closed on a Alt-F4 event
@PCMan

**Comment by pmattern** [comment] 2015-07-12 14:00
Just curious: what's the actual problem you're facing? Just tried to provoke some faulty behaviour by closing PCManFM-Qt windows by Alt+F4 to no avail.

**Comment by agaida** [comment] 2015-07-12 15:12
no app running - Alt-F4 - upps, there goes the desktop background and the folders ...

**Comment by pmattern** [comment] 2015-07-12 18:04
Just tried to reproduce this: Arch Linux x86_64 "bare metal" and KVM/QEMU VM, Arch Linux i686, Lubuntu 15.04 and Sicuction in KVM/QEMU VM, all up-to-date and latest LXQt checkouts from their typical sources - to no avail.
No apparent problems, no error messages in systemd journal, PID of PCManFM-Qt stays the same!?

Btw. doesn't --desktop involve running PCManFM-Qt in daemon mode?

(Also wanted to test LXQt on Debian stable and testing from their respective Siduction repo but can't get either of them running reasonably right now. Different story, of course.)

**Comment by agaida** [comment] 2015-07-12 20:35
ok - after testing a little bit more - this doesn't happend with openbox - but with xfwm4 
no other window managers tested so far

**Comment by agaida** [comment] 2015-07-12 20:39
another strange thing: if i start a 'normal' pcmanfm-qt - this will start the pcmanfm-qt --desktop process too.

**Comment by pmattern** [comment] 2015-07-28 20:07
Confirmed running Xfwm4. Corresponding messages in systemd journal are
```
pcmanfm-qt[462]: delete ProxyFolderModel
pcmanfm-qt[462]: aboutToQuit
lxqt-session[421]: Process "Desktop" ( LxQtModule(0x19337d0) ) exited correctly.
```
Analogue findings can't be made running Xfwm4 on Xfce and the problem ceases if `Alt+F4` gets action "close window" unassigned which it had been assigned on Openbox as well when it did not appear, btw.
Looks indeed as if that action got forwarded to the wrong object.

**Comment by agaida** [comment] 2015-09-27 01:05
closing with a commit would satisfy me more :D

**Comment by pmattern** [comment] 2015-09-27 09:39
Sure. But it was just the dupe I closed.

**Closed** 2015-09-27 13:53 UTC

**Comment by Vandino86** [comment] 2024-10-06 04:04
On Void Linux (x86_64-musl), I have this issue when using Xfwm, but not when using Openbox. I'm not sure why this is since this was apparently fixed 9 years ago. Here is what I have currently installed, if that helps:

linux6.6-6.6.54_1
lxqt-2.0.0_1
pcmanfm-qt-2.0.0_1
xfwm4-4.18.0_1
openbox-3.6.1_5

**Comment by stefonarch** [comment] 2024-10-06 12:39
This wasn't solved afaik. 
I logged into x11 with xfwm4 and it's like this also here.
That's a similar issue of xfwm4 as kwin has when showing the desktop (it doesn't minimize PCManFM-Qt windows).

**Comment by Vandino86** [comment] 2024-10-06 20:17
Should this issue be re-opened, then?

**Comment by stefonarch** [comment] 2024-10-06 21:24
No, as it is an issue of xfwm4 only  and we won't add code for circumvent other apps issues most probably.

**Comment by tsujan** [comment] 2024-10-06 22:00
Detailed explanation:

9 years ago, https://github.com/lxqt/pcmanfm-qt/commit/875e18ba982bb14710ada1a4616043ea128c9d80 was made as a simple workaround for this and similar cases. It was a *workaround*, not a "fix", because the problem wasn't in pcmanfm-qt: an X11 WM should be able to distinguish between a *desktop window* from an ordinary window and not close the former with a shortcut for closing the latter.

Starting with Qt6, `QCoreApplication::quit()` calls `closeEvent()` when the app window is visible, such that the above workaround causes serious troubles (if I remember correctly, it caused a crash once). So, I removed it and upgraded the code to Qt6.

For various reasons, the transition from Qt5 to Qt6 couldn't be done through multiple git commits — I did it in several months inside a WIP PR — and so, there's no single commit in the git history that shows the above-mentioned change; hence this explanation.
