### ISSUE TITLE
Places vs. Directory Tree: allow for remembering selection

### ISSUE THREAD

**Issue by pmattern** [lxde/pcmanfm-qt#157] opened 2015-03-03 22:46 UTC
Right now PCManFM-Qt will always display "Places" view in left pane upon launch.
I think it would be good if this could be tweaked. Either by remembering what had been set when PCManFM-Qt was left before or by having it configurable (which would imho be the better choice).

**Comment by ufleisch** [comment] 2015-06-23 18:39
The problem is that when logging out, PCManFM-Qt is terminated by SIGTERM. The `aboutToQuit()` signal is not emitted in this case and therefore the settings are not saved. If have added a commit which installs a SIGTERM handler which then `quit()`s the `QApplication` so that aboutToQuit() is signaled and the settings are saved.

**Comment by pmattern** [comment] 2015-06-23 19:13
ufleisch/pcmanfm-qt@a84ad62 works as expected here.

**Comment by ufleisch** [comment] 2015-06-25 20:01
I have rebased my branch on master and reorganized the commits for the two referenced issues.

**Comment by pmattern** [comment] 2015-06-25 20:33
FWIW no problems due to rebasing. Still everything working as expected here.

**Comment by PCMan** [comment] 2015-07-09 05:04
merged.

**Closed by PCMan** 2015-07-09 05:04 UTC
