### ISSUE TITLE
Path bar switches automatically to "Path buttons" mode after reboot. 

### ISSUE THREAD

**Issue by githubtefo** [lxde/pcmanfm-qt#445] opened 2017-01-27 20:03 UTC
Hello,
since v0.11.3, when I restart the lxqt- session, the Path bar changes from Location mode to buttons mode.
Is there any way to prevent this?
Thanks in advance!

**Comment by tsujan** [comment] 2017-01-27 20:10
Check View → Path Bar → Location!

**Comment by githubtefo** [comment] 2017-01-27 20:14
tsujan, thanks for your answer. I changed to Location mode but every time I restart the session the Path bar returns to Buttons Mode.

**Comment by tsujan** [comment] 2017-01-27 20:19
I just changed that setting, logged out, logged in again and the new setting was preserved. How do you restart the lxqt-session?

**Comment by githubtefo** [comment] 2017-01-27 20:23
By rebooting the whole system (Arch/lx-qt).

**Comment by tsujan** [comment] 2017-01-27 20:27
Confirmed!

This bug isn't in pcmanfm-qt (although a workaround is possible in pcmanfm-qt). The bug may be in lxqt-session. @luis-pereira, @palinek ?

**Comment by tsujan** [comment] 2017-01-27 20:31
pcmanfm-qt saves its settings on quitting. It seems that rebooting the system dosn't make it quit. I don't see a crash either.

**Comment by luis-pereira** [comment] 2017-01-27 21:42
@palinek I'm away from my dev machine. I can certainly look at it Monday.

**Comment by luis-pereira** [comment] 2017-01-27 21:52
I did a logout and a login and was not able to reproduce it.

**Comment by tsujan** [comment] 2017-01-27 21:53
@luis-pereira, it's about shutdown/reboot, not logout/login.

**Comment by palinek** [comment] 2017-01-27 23:53
I can confirm, that the lxqt-session isn't properly stopped in case of reboot here.

You can check/confirm it by enabling the debug output for lxqt-session (by setting the environment variable `QT_LOGGING_RULES="lxqt-session.debug=true"` in e.g. `startlxqt`). In case of reboot [these messages](https://github.com/lxde/lxqt-session/blob/master/lxqt-session/src/lxqtmodman.cpp#L357) aren't shown in the output.

Ending the session was fixed here -> lxde/lxqt-session/@302843e86512b38f9809c2119f15e02ffb6c3629. But now it doesn't seem to work any more.

That leads to the question how is the session stopped by its master/parent/display manager/systemd?

**Comment by palinek** [comment] 2017-01-28 00:18
I'm on lightdm... the parent of lxqt-session is `lightdm --session-child 14 21` in my case.

I can be wrong, but based on this source -> http://bazaar.launchpad.net/~lightdm-team/lightdm/trunk/view/head:/src/session-child.c#L667.... I assume that the session should be normaly stopped by the SIGTERM.

**Comment by palinek** [comment] 2017-01-28 00:49
Funny... with the manually built `lxqt-session` from current master, the `LXQtModuleManager::logout()` is called correctly on reboot, but with the binary package not. But the package is up-to-date with master:
```
$ apt policy lxqt-session
lxqt-session:
  Installed: 0.11.2~1-g7d464fb-2
  Candidate: 0.11.2~1-g7d464fb-2
  Version table:
 *** 0.11.2~1-g7d464fb-2 500
        500 http://lxqt.debian.net/debian lxqt-snapshots/main amd64 Packages
        100 /var/lib/dpkg/status
     0.11.1-2 500
        500 http://ftp.sk.debian.org/debian unstable/main amd64 Packages
```

**Comment by pmattern** [comment] 2017-01-28 01:11
FWIW I can confirm the problem running latest VCS commits including lxde/lxqt-session@7d464fb from the AUR on Arch Linux as well.

**Comment by tsujan** [comment] 2017-01-28 07:50
> Funny... with the manually built lxqt-session from current master, the LXQtModuleManager::logout() is called correctly on reboot...

My LXQt package are all manually built.

It seems that `LXQtModuleManager::logout()` isn't called anymore, whether in Arch or in Debian, whether with sddm or with lightdm. Something fundamental might have been changed.

**Comment by tsujan** [comment] 2017-01-28 10:16
Please try https://github.com/lxde/pcmanfm-qt/pull/447! Although I don't think that this is a bug in pcmanfm-qt, that patch should prevent such problems.

**Comment by tsujan** [comment] 2017-01-28 17:33
So, it's a random issue, @palinek's observation confirms that (because manually build packages can't be different from binary ones).

Anyhow, https://github.com/lxde/pcmanfm-qt/pull/447 should fix the issue completely. I'm testing it but it needs more tests because I shut down the computer only once a day ;)

**Comment by githubtefo** [comment] 2017-01-28 18:34
Ok @tsujan, I will test the solution when the issue returns and persists like yesterday, given this way I can confirm #447 repairs it.

**Comment by tsujan** [comment] 2017-01-29 08:32
Bad news: https://github.com/lxde/pcmanfm-qt/pull/447 had no effect on this because pcmanfm-qt already had a SIGTERM handler.

Either the problem should be fixed in lxqt-session or pcmanfm-qt should save its settings on the fly, the latter just being a (partial) workaround.

**Comment by tsujan** [comment] 2017-01-29 09:21
This may be a systemd issue: https://bugzilla.redhat.com/show_bug.cgi?id=1394937

**Comment by tsujan** [comment] 2017-01-29 14:52
Latest results of some tests:

It seems that SIGHUP cancels SIGTERM on shutdown/reboot. Once I removed SIGHUP from lxqt-session → `sessionapplication.cpp` and *ignored* it with `signal(SIGHUP, SIG_IGN);` in pcmanfm-qt → `application.cpp`, pcmanfm-qt saved its settings on shutdown/reboot.

How SIGHUP has become an obstacle, I don't know.

**Comment by tsujan** [comment] 2017-01-30 00:43
The above-mentioned "solution" (removing SIGHUP from lxqt-session and ignoring it in pcmanfm-qt) worked for 5 consecutive reboots but failed with the 6th. I've run out of ideas for now, hoping that @palinek or @luis-pereira will find a solution/workaround (calling `LXQtModuleManager::logout()` deliberately?).

If the problem is in systemd, we should take on-the-fly saving seriously, IMO.

**Comment by palinek** [comment] 2017-01-30 07:49
If it is really an issue of init system (systemd in this case), where it is "hardkilling"(SIGKILL) the session w/o giving it enough time after SIGTERM to shutdown... then I believe there is no solution nor workaround.

**Comment by tsujan** [comment] 2017-01-30 12:54
@palinek 

I may be lost but is there any way to call `LXQtModuleManager::logout()` inside LeaveDialog's connections (after `close();` and before `mPowerManager->...;`?

**Comment by palinek** [comment] 2017-01-30 14:05
> I may be lost but is there any way to call LXQtModuleManager::logout() inside LeaveDialog's connections (after close(); and before mPowerManager->...;)?

Yes, you may call the logout via DBus, but IMO:
- if it will be a synchronous call -> the session will be shut down which causes shuting down the X and the leave dialog will fail somewhere deep in the Qt
- if it will be asynchrnous -> the session still might have not enough time to shutdown before it is killed

**Comment by luis-pereira** [comment] 2017-02-02 23:18
Tried to reproduce it 5 times without success!! 
Will continue, tomorrow.

**Comment by tsujan** [comment] 2017-12-15 10:01
Even if this could be reproduced --it can't here -- it would definitely be a systemd issue. So, closing it.

**Closed by tsujan** 2017-12-15 10:01 UTC
Labels: bug
