### ISSUE TITLE
Wallpaper is overlapping.

### ISSUE THREAD

**Issue by huki** [lxde/pcmanfm-qt#440] opened 2017-01-07 14:30 UTC
My resolution is 2560x1440.
My wallpaper used the graphic file which is 2560x1440.
And then the wallpaper is overlapping like this.
![screen](https://cloud.githubusercontent.com/assets/150319/21742383/c684e61a-d528-11e6-94c3-fabc8abd3206.png)

**Comment by tsujan** [comment] 2017-01-07 14:43
This is a duplicate of several other reports. See https://github.com/lxde/lxqt/issues/1027.

In short, it's a Qt5 bug.

**Closed by tsujan** 2017-01-07 14:43 UTC
