### ISSUE TITLE
File removing is very slow

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#538] opened 2017-07-16 10:42 UTC
Suspecting that pcmanfm-qt has a poor performance when removing a large amount of files (let's say a single folder with many files/folders inside), I decided to create a simple Qt project that just calls QDir::removeRecursively(). The results:

pcmanfm-qt: 8 seconds
qt only: less than 1 second

I know that pcmanfm-qt does more than just removing (it shows the current file name being removed, the progress bar, etc). But, still, this is waaay slower than we could expect from such a simple task. What you think?

**Comment by tsujan** [comment] 2017-07-16 10:53
I can't confirm this. Removing large folders containing many files is something I may do often -- because of compiling heavy projects like Qt, kwin, EFL, etc. -- and yet I don't see any slowness at all. Actually, I see slowness when I do the same things with Dolphin.

**Comment by fulalas** [comment] 2017-07-16 11:04
Did you try a new Qt project as I said? Or simply removing through the terminal?

**Comment by tsujan** [comment] 2017-07-16 11:21
I wouldn't compare file removal in a file manager with file removal in a simple Qt project. Take a fast look at the libfm-qt code and you'll know why. What I know for sure is that there have been several occasions when I had to remove really heavy folders containing many files (GB is size) and they were removed quickly in pcmanfm-qt. That's while, with Dolphin and under KDE, I had to wait for Plasma to tell me that files were removed. So, contrary to what you say, pcmanfm-qt has always been fast for me we it comes to file removal.

**Comment by tsujan** [comment] 2017-07-16 11:32
A few minutes ago, I found the compilation folder of `efl-1.19.0` with a GB size. It was in my 6th partition and I'd forgotten to remove it. I right clicked on it, moved it to Trash *instantly* and emptied Trash *instantly*.

**Comment by fulalas** [comment] 2017-07-16 11:48
@tsujan, you always try to say 'for me it works, so the problem doesn't exist'. I know it's tough to hear that, but, please, try to think out of the box for a while, man. People have different machines, scenarios, necessities, ideas, etc. The world goes beyond our personal view. 

Pcmanfm-qt could be the fastest FM in the world regarding file removing, still, there's obviously a problem if we can do the same task with 1/8 of the time using another method. But, hey, take a look at a real world FM that does this job way faster than pcmanfm-qt: https://pkgs.org/download/spacefm . It would be really great if you could test it and compare with pcmanfm-qt instead of just saying theories and personal feelings ('I feel it's fast, so it is'...). I'm talking about numbers, something we can measure.

Although removing to trash is a moving operation (so we can't expect anything different than _instantly_), emptying trash was indeed a good test you did because it showed that the issue I'm talking about is probably with the dialog that shows current files being removed, progress bar, etc., since when emptying trash we don't see this and the performance is beautiful. :)

**Comment by agaida** [comment] 2017-07-16 11:51
Please, no references to dead projects written by wannabe's. Thanks.

**Comment by fulalas** [comment] 2017-07-16 11:53
@agaida, is this a joke? I'm giving a performance reference for a single delete action, for god's sake. I don't care who made this program, if it's dead or anything like that. Let's keep focus, guys.

**Comment by agaida** [comment] 2017-07-16 11:57
It isn't a joke - but if the author is a liar who spread false claims around the net it's a very personal thing. The thing that would be interesting is: Do you really deleted the files or moved them to the trash bin.

**Comment by tsujan** [comment] 2017-07-16 11:58
> @tsujan, you always try to say 'for me it works, so the problem doesn't exist'. 

That's not true. On the one hand, a simple look to my replies shows that I like to find and fix bugs. On the other hand, when I say , "it works for me," I mean it works for me; I don't *deny* that it may not work for you for whatever reason unknown to me. It's your responsibility to provide us with a clear explanation in your reports, WE DO NOT HAVE TELEPATHY.

**Comment by tsujan** [comment] 2017-07-16 12:00
Most of the time, you give poor reports and change your statement in the middle of discussion. That's time-consuming and counter-productive.

**Comment by fulalas** [comment] 2017-07-16 12:03
@agaida, as I said: I'm not using trash.

@tsujan, it's true that you work really hard on LXQt -- probably the most active developer here. I will never question that. Indeed I admire you effort a lot. But it's also true that you like to mark as invalid/solved bug reports that you can't replicate at first sight. I can give you countless examples, but that's not the point here, I think. And sorry if I give you bad reports. Sometimes it's not clear what's the specific scenario where a bug happens. You're a developer and know that very well :)

**Comment by tsujan** [comment] 2017-07-16 12:07
> @agaida, as I said: I'm not using trash.

Read your first comment and find the word "Trash" or the sentence "I'm not using trash" in it! Without sticking to logic, there can be no productive discussion, let alone bug fixing.

I don't need anyone's admiration to work on any project. I do it because it's fun. Bad reports interfere with that. Of course, you've had good reports too. So, you don't need me to tell you what's the difference between them.

**Comment by fulalas** [comment] 2017-07-16 12:08
Because trash is a moving operation...

**Comment by fulalas** [comment] 2017-07-16 12:10
Read again the untouched title of this issue: file **REMOVING** is very slow. I'm not saying file moving, file copying, file creation, file anything else.

**Comment by tsujan** [comment] 2017-07-16 12:12
> Because trash is a moving operation... Read again the untouched....

That's obviously a rationalization. You expect mind-reading from me.

Anyway, I can't do anything when it isn't clear what the problem is -- and mind-reading is everything but fun.

**Comment by fulalas** [comment] 2017-07-16 12:13
Hahaha! Nevermind...

**Comment by tsujan** [comment] 2017-07-16 12:13
From now on, please use the template to report a bug. Closing this.

**Closed by tsujan** 2017-07-16 12:13 UTC

**Comment by tsujan** [comment] 2017-07-16 12:35
This isn't about this report but something interesting about "IgnorantGuru" -- and I think it's fun.

Years ago, he wrote an article about why and how gtk and gnome was "bad". I agreed with him although I saw an air of unreasonable emotions both in his article and in his site. In another article, he wrote about how Qt was dangerous too and why it was so unfortunate that most developers started to rewrite their programs in Qt. I just left a comment there, telling that Qt was really cool. He attacked me with emotional, insulting words and in response, I said very politely I was sorry to think that such places were for rational discussions. I was attacked again but didn't replied. After that I learned how he and his "fans" thought and never read his articles again, let alone leaving comments. 

I was also impressed by how he though that he'd written the most important program in the world -- namely spacefm ;)

**Comment by tsujan** [comment] 2017-07-16 13:22
Ha ha, found it: https://igurublog.wordpress.com/2014/01/25/gtk-fesses-up-this-aint-for-you-qt-takes-over-the-world/. Read from "I agree that, unfortunately,..."

**Comment by agaida** [comment] 2017-07-16 14:19
Nice. Ok, back in time: https://igurublog.wordpress.com/2011/02/19/archs-dirty-little-notso-secret/
Two additions - i wrote only one or two posts at all in the arch dev-list. :) That mutated to:

>  Several developers had a cavalier and careless attitude about their users’ security in general, and I find attitude is very important when it comes to developing security mechanisms. I like to know the devs behind the system I use take that responsibility seriously. This was not what I was expecting to see. Many of the developers also displayed either ignorance or a poor understanding of the importance of package signing, and even other security practices in general [bold below mine]:
> 
> Alf Gaida: “For me it makes not a big difference if a package is signed or not. It’s a nice to have feature and I would be glad if someone would implement it. But for me it has a very low priority.”

My respose:
> Its nice to read from me that i’m a arch developer. Funny too. Only because i wrote my opinion in the dev-List, i’m be responsible. Fuck it. And delete the guru from your name. Ignorant as a name and program make more sense.
> 
> For the records. I never ever wrote a line for any official arch package. Esp. not for pacman. For security reasons these are good news for arch.
> 
> Comment by alfgaida | March 27, 2012 

And i'm still pissed about after these years.

**Comment by tsujan** [comment] 2017-07-16 14:36
@agaida Yes, the same odd reaction to an opposite point of the view! "IgnorantGuru" enjoys being admired by his "fans" and can't tolerate a real discussion. And his "fans" give him what he wants: a system as closed as gnome3 -- but maybe gnome3 isn't so closed anymore. It has always been interesting to me how emotional opposition uses the same "techniques" it opposes: ignorance, irrationality, self-congratulation... which result in a closed system (of mind). Ignore logic and you could say anything you want to -- as Aristotle knew 2500 years ago.

**Comment by tsujan** [comment] 2017-07-16 15:08
BTW, this is an example of a clear report: https://github.com/lxde/pcmanfm-qt/issues/539
