### ISSUE TITLE
Symlink representation doesn't follow actual status of link until the symlink itself is renamed

### ISSUE THREAD

**Issue by aramazano** [lxde/pcmanfm-qt#635] opened 2018-01-01 21:01 UTC
In pcmanfm-qt, if you rename the real file a symlink is pointing to, i.e. break the link, the affected symlink still shows --incorrectly-- as a healthy link. Only when you rename this broken symlink too, then it starts to show --correctly-- as a broken link.

After this, if you re-rename the real file to its original name, i.e. restore the link, affected symlink still shows as a broken link. Only when you rename the symlink then it starts to show again as a healthy link.

PS: Might be related to #607?

##### System Information

* Distribution & Version: Debian Stretch (9.3)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.7.1
* lxqt-build-tools Version: ?
* libqtxdg Version: ?
* libfm-qt Version: libfm-qt3:amd64 0.11.2-1
* Package version: PCManFM-Qt 0.11.3

**Comment by tsujan** [comment] 2018-01-01 21:12
You should reload the folder to update the state of a symlink.

This is not a bug. Searching for all symlinks of a file inside a folder after that file is renamed or removed or updating a whole folder when one of its files is renamed is a potentially heavy job and shouldn't be done. Closing this.

**Closed by tsujan** 2018-01-01 21:12 UTC

**Comment by aramazano** [comment] 2018-01-01 21:23
Somehow I didn't think of reloading the folder after the operation - my fault, and I'm sorry to open an issue for this. But on the other hand, I did close pcmanfm-qt and relaunced it to see if it changed symlink representation, and it didn't. Possibly this may be a caching issue - I don't know operation details of pcmanfm-qt. So is it possible to re-open this as "pcmanfm-qt doesn't invalidate its cache at launc" or something similar, if it's relevant?

**Comment by tsujan** [comment] 2018-01-01 21:30
> But on the other hand, I did close pcmanfm-qt and relaunced it to see if it changed symlink representation, and it didn't

The problem is that you use a very old version of pcmanfm-qt. Many fundamental changes have happened both under the hood and on the surface since that version, which means so many bugs are fixed.

**Comment by aramazano** [comment] 2018-01-01 21:47
Sorry for this. I plan to upgrade to Debian testing (Buster) around the end of this month, with has reasonably newer release of lxqy components. Then I will be able to report more relevant issues, hopefully. Stopping bug reporting until Buster upgrade.
