### ISSUE TITLE
[Regression] Fail to build libfm-qt after the lxqt-build-tools and cmake updates

### ISSUE THREAD

**Issue by PCMan** [lxde/pcmanfm-qt#416] opened 2016-12-03 14:19 UTC
After installing the latest lxqt-build-tools in 45ce2671283f48f6435aa247a3254b0921b52b8f and updated libfm-qt to c10100a8f0b58f00624f962d0bf151afefa8d475, I'm no longer to build libfm-qt.

@luis-pereira would you please take a look at this? Thanks a lot.

My command line:
> cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=release ..

Detailed error messages:
```
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found XCB: /usr/lib64/libxcb.so  
-- Found Fm: /usr/lib64/libfm.so (found suitable version "1.2.4", minimum required is "1.2.0") 
-- Found MenuCache: /usr/lib64/libmenu-cache.so (found suitable version "1.0.2", minimum required is "0.4.0") 
-- Building libfm-qt with Qt 5.7.0
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found Git: /usr/bin/git (found version "2.10.2") 
-- Pulling the translations...
From https://github.com/lxde/translations
 * branch            master     -> FETCH_HEAD
Already up-to-date.
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
CMake Error in src/CMakeLists.txt:
  Target "fm-qt" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/pcman/lxqt/libfm-qt/src/"

  which is prefixed in the source directory.


CMake Error in src/CMakeLists.txt:
  Target "fm-qt" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/pcman/lxqt/libfm-qt/src/"

  which is prefixed in the source directory.


-- Generating done
-- Build files have been written to: /home/pcman/lxqt/libfm-qt/build
[pcman@arch-pc build]$ 
```

Then `make` gave me this:
```
[pcman@arch-pc build]$ make
[  1%] Automatic moc for target fm-qt
Generating moc source moc_appchoosercombobox.cpp
Generating moc source moc_appchooserdialog.cpp
Generating moc source moc_appmenuview.cpp
Generating moc source moc_cachedfoldermodel.cpp
Generating moc source moc_colorbutton.cpp
Generating moc source moc_createnewmenu.cpp
Generating moc source moc_dirtreemodel.cpp
Generating moc source moc_dirtreeview.cpp
Generating moc source moc_dndactionmenu.cpp
Generating moc source moc_editbookmarksdialog.cpp
Generating moc source moc_execfiledialog_p.cpp
Generating moc source moc_filemenu.cpp
Generating moc source moc_filemenu_p.cpp
Generating moc source moc_fileoperation.cpp
Generating moc source moc_fileoperationdialog.cpp
Generating moc source moc_filepropsdialog.cpp
Generating moc source moc_folderitemdelegate.cpp
Generating moc source moc_foldermenu.cpp
Generating moc source moc_foldermodel.cpp
Generating moc source moc_folderview.cpp
Generating moc source moc_folderview_p.cpp
Generating moc source moc_fontbutton.cpp
Generating moc source moc_icontheme.cpp
Generating moc source moc_mountoperation.cpp
Generating moc source moc_mountoperationpassworddialog_p.cpp
Generating moc source moc_mountoperationquestiondialog_p.cpp
Generating moc source moc_pathbar.cpp
Generating moc source moc_pathbar_p.cpp
Generating moc source moc_pathedit.cpp
Generating moc source moc_pathedit_p.cpp
Generating moc source moc_placesmodel.cpp
Generating moc source moc_placesview.cpp
Generating moc source moc_proxyfoldermodel.cpp
Generating moc source moc_renamedialog.cpp
Generating moc source moc_sidepane.cpp
Generating moc source moc_utilities_p.cpp
Generating moc compilation fm-qt_automoc.cpp
[  1%] Built target fm-qt_automoc
Scanning dependencies of target fm-qt
[  2%] Building CXX object src/CMakeFiles/fm-qt.dir/libfmqt.cpp.o
In file included from /usr/include/libfm/fm.h:28:0,
                 from /home/pcman/lxqt/libfm-qt/src/libfmqt.cpp:20:
/usr/include/libfm/fm-app-info.h:26:21: fatal error: gio/gio.h: No such file or directory
 #include <gio/gio.h>
                     ^
compilation terminated.
make[2]: *** [src/CMakeFiles/fm-qt.dir/build.make:171: src/CMakeFiles/fm-qt.dir/libfmqt.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: src/CMakeFiles/fm-qt.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
[pcman@arch-pc build]$ 
```

**Comment by tsujan** [comment] 2016-12-03 14:29
@PCMan 
Strange! Today I needed to update my libfm-qt installation and it was compiled only after I updated lxqt-build-tools too.

**Comment by luis-pereira** [comment] 2016-12-03 15:46
@PCMan That's odd. Just built it right now without glitches.
Did you start with a clean build directory ?

**Comment by luis-pereira** [comment] 2016-12-03 15:51
@PCMan The issue is related to the Fm and MenuCache detection.
Mine gives:
```
-- Found Fm: /home/lpereira/opt/lib/libfm.so;/usr/lib64/libgthread-2.0.so;/usr/lib64/libgio-2.0.so;/usr/lib64/libgobject-2.0.so;/usr/lib64/libglib-2.0.so (found suitable version "1.2.4", minimum required is "1.2.0") 
-- Found MenuCache: /home/lpereira/opt/lib/libmenu-cache.so;/usr/lib64/libglib-2.0.so (found suitable version "1.0.2", minimum required is "0.4.0") 
```
Yours is missing the glib dependencies. Pls make sure lxqt-build-tools is properly installed and you started with a clean libfm-qt build directory.

**Comment by luis-pereira** [comment] 2016-12-23 00:43
@PCMan Solved, right ?

**Comment by luis-pereira** [comment] 2017-03-08 11:37
Solved. Closing.

**Closed by luis-pereira** 2017-03-08 11:37 UTC
Labels: bug
