### ISSUE TITLE
Desktop Preferences: menus provided by window manager not displayed any more (suspect Qt 5 bug)

### ISSUE THREAD

**Issue by pmattern** [lxde/pcmanfm-qt#197] opened 2015-07-16 10:50 UTC
Setting "Show menus provided by window managers..." in GUI "Desktop Preferences", Tab "Advanced" (`pcmanfm-qt --desktop-pref=advanced`) isn't working as expected any more on up-to-date Arch Linux systems running all LXQt components from latest Git checkouts and Openbox.

If it's checked clicking an arbitrary mouse button on the desktop doesn't have any effect at all.
Setting 'ShowWmMenu' in ~/.config/pcmanfm-qt/lxqt/settings.conf gets toggled by running `pcmanfm-qt --desktop-pref=advanced` as usual.

Regression testing strongly suggests the problem is caused by Qt 5.*5*:
It can be seen if LXQt components as stated above get compiled against Qt 5.5.0 but not if the very same components get compiled against Qt 5.4.2.
On the other hand it can be seen if e. g. df5b2ba gets compiled against Qt 5.5.0 on a system as stated above otherwise but it couldn't be seen when the same commit was the actual one some weeks ago and as such compiled against Qt 5.4.2.

**Comment by PCMan** [comment] 2015-09-12 12:23
Confirmed.
The Qt nativeEventFilter() does not seem to receive the button press events from XCB.
This might be a regression bug of Qt 5.5. :-(

**Comment by PCMan** [comment] 2015-09-12 12:26
Alternatively, we can try to install the event filter on DesktopWindow rather than QDesktopWidget.
Previously we install the filter on QDesktopWidget, which might have been changed.

**Comment by PCMan** [comment] 2015-09-12 14:25
Luckily I've found a workaround.

**Comment by PCMan** [comment] 2015-09-12 14:26
The current code in git works again, but I leave the bug open since it's suspected that there's a regression bug in Qt 5.5. After we reported this to the upstream Qt developers, we can close it.

**Comment by pmattern** [comment] 2015-09-12 15:33
Workaround is doing its job. At last a reasonable way to access a list of all running applications is available again - so thanks a lot.

Btw. shouldn't this be 5.*5* in the modified title?

**Comment by PCMan** [comment] 2016-01-15 11:01
Well, I know the cause of the problem.
It's not a bug of Qt 5. Instead, it's a change of Qt internal implementation.
Qt now uses xinput2 to handle mouse input events so that's why we never receive XCB_BUTTON_RELEASE events from xcb.
To handle the event, we need to intercept XCB_GE_GENERIC instead, and add specialized handling for xinput2, which is too complicated.
The current workaround works well, so let's close the issue.

**Closed by PCMan** 2016-01-15 11:01 UTC
Labels: bug

**Comment by PCMan** [comment] 2016-01-15 14:47
Related issue.
https://github.com/lxde/lxqt/issues/688
