### ISSUE TITLE
Allow to choose side icons size with context menu too

### ISSUE THREAD

**Issue by goetzc** [lxde/pcmanfm-qt#334] opened 2016-04-04 00:46 UTC
Right now it is possible to choose the side panel icon size from within a submenu in preferences, but it is not so intuitive as directly right-clicking an icon in side panel and choosing one of the available icon sizes.

An example:
![panel icon size in context menu](https://cloud.githubusercontent.com/assets/2220440/14236026/bc111748-f9d3-11e5-8900-7683fc3cfbfc.png)

**Comment by tsujan** [comment] 2016-04-04 08:18
IMO, it isn't so intuitive but only what Dolphin does and so, a matter of taste.

**Comment by pmattern** [comment] 2016-04-04 12:02
I agree with @tsujan that this is a matter of taste and that configuring the icon size from FHS objects' context menus doesn't make really sense.
IMO it's a feature that's not needed to frequently and as such rather bloating the context menus.

But nevertheless I think the handling of icons does need improvement.
The purpose of the groups defined in Preferences isn't remotely obvious. E. g. the "big icons" in terms of Preferences - Display are covering the desktop as well but this isn't stated anywhere in the UI. Maybe the UI components these groups of icons apply to could be stated by a tooltip?
Also, I think setting the size of desktop icons should be possible from within `pcmanfm --desktop-pref=foo` / dialogue "Desktop Preferences" which is accessible from the desktop's context menu.

**Comment by tsujan** [comment] 2016-04-04 13:34
> But nevertheless I think the handling of icons does need improvement.

I agree. Since desktop has a separate font size, it's logical to give it a separate icon size too. I'll see whether that can be done without bloating the code.

**Comment by pmattern** [comment] 2016-04-07 15:51
When the same shortcut gets assigned to several actions `lxqt-config-globalkeyshortcuts` prints one of the shortcuts in bold but doesn't really throw a warning.
This should eventually be changed, too.

**Comment by tsujan** [comment] 2016-04-11 14:04
Apparently, we agree that menus shouldn't be cluttered, on the one hand, and @pmattern's suggestion is implemented by https://github.com/lxde/pcmanfm-qt/pull/335, on the hand. So, this issue can be closed.

**Closed by tsujan** 2016-04-11 14:04 UTC
Labels: enhancement

**Comment by pmattern** [comment] 2016-04-12 17:55
Now that the size of desktop icons can be set from `pcmanfm-qt --desktop-pref=general` I cannot see an effect of "Size of big icons" in Preferences - Display any longer.
If so, shouldn't this setting be dropped? Otherwise, can anyone give me a hint which icons this setting is still referring to?

Wouldn't it eventually be good if the desktop icons' size could be tweaked from a new topic in Preferences - Display in addition to `pcmanfm-qt --desktop-pref=general`?

While at it I stumbled upon another finding not strictly related to this issue: "Size of thumbnails" doesn't seem to have any effect at all here. Again, can anybody confirm or give me a hint what the effect of this setting is meant to be?

**Comment by tsujan** [comment] 2016-04-12 18:10
@pmattern
"Size of big icons" and "Size of thumbnails" are for the icon view and thumbnail view of PCManFM, respectively. The latter is for those who prefer very big icons. None of them is for desktop, of course.

**Comment by pmattern** [comment] 2016-04-12 18:29
@tsujan 
Confirmed. Thanks.

And how about the proposal to explain the effect of those various settings "Size of [...]" e. g. in a tooltip? I still think their meaning is all but obvious.

**Comment by tsujan** [comment] 2016-04-12 18:39
@pmattern 
Yes, good idea! All elements of a config GUI should have informative tooltips. If nobody skilled at giving concise descriptions is going to add them, I will.

**Comment by tsujan** [comment] 2016-04-13 11:40
@pmattern
I think https://github.com/lxde/pcmanfm-qt/pull/339 is enough -- the purpose of other elements can be easily understood from their texts.
