### ISSUE TITLE
Give option to stop deletion of files if an error occurs

### ISSUE THREAD

**Issue by FrederikLauber** [lxde/pcmanfm-qt#512] opened 2017-06-20 12:39 UTC
Hi,

sometimes deleting many files with pcmanfm-qt via "CTRL+A, Shift-Del", instead of deleting the files, pcmanfm-qt will just complain that the files are not there.
The problem is, that you now have an error dialog which you have to close and it immediately pops up again with the next file. The only way to get out is either to click ok for each file (in my case 17k files) or kill pcmanfm-qt and then restart because this breaks a lot of other stuff.

I attached an screenshot of the situation.

![dsaads](https://user-images.githubusercontent.com/17728264/27333440-37a586a6-55c6-11e7-9879-63a03d216e41.png)

**Comment by tsujan** [comment] 2017-06-20 12:51
If pcmanfm-qt shows a file that doesn't exist, this is about https://github.com/lxde/pcmanfm-qt/issues/508. If the file exists and belongs to the user, it should delete it. If the file exists and doesn't belong to the user, it should show that dialog. Which is the case? Do you have an up-to-date version of pcmanfm-qt (0.11.3)?

**Comment by FrederikLauber** [comment] 2017-06-20 13:40
Uptodate pcmanfm-qt (0.11.3). Running on Arch if it matters.

The problems is apparently the selection with CTRL+A. If you do that and try to delete the files, it will complain that they are not there but in fact they still are.

So after I killed the process, the files are still there (you can even see it in the screenshot, it complains it cannot find Burnsample_31.pickle which can be seen in the background and checking with the console also shows it.

If I select the files manually (i.e. drag my mouse around and select them that way), it works as expected. Do I use CTRL+A to select all files, it will complain that it cannot find any file.

**Comment by tsujan** [comment] 2017-06-20 14:01
Strange! I cannot reproduce it with ~100 files. Does the number of files matter? Does it happen always? Do those files that aren't deleted have a specific property?

**Comment by FrederikLauber** [comment] 2017-06-20 14:31
Hi,

after playing around with this, I have to say, the file number does not matter.
It happens even with a single file.
Strangest part, it will complain exactly 4 times for each file you want to delete that it is not there and on the 4 "File not found error" it will actually delete the file.

**Comment by tsujan** [comment] 2017-06-20 16:29
I made 5 folders with various number of files in them (from 1 to 100) and when I did `CTRL+A` + `Shift-Delete` inside them, the confirmation dialog appeared, I chose "Yes", and all files were deleted without problem.

The issue you've encountered may have a special but hidden cause which doesn't exist on my system. One thing that comes to my mind is recompilation of the latest version against Qt 5.9. Arch LXQt packages are still compiled against 5.8 while the Qt version is 5.9.

**Comment by fulalas** [comment] 2017-06-30 13:02
I'm aware of this issue (very annoying, btw). It's easily reproducible.

1- create a new folder;
2- create some files inside it;
3- select all of them and hit delete, but don't confirm nor cancel;
4- open a terminal and remove all files;
5- go back to the dialog and finally confirm it;

Of course pcmanfm-qt is supposed to show an error. The problem is that user doesn't have an option to cancel this operation. Instead, he needs to face endless error dialogs.

There are other scenarios where this issue appears. I'm just giving an easy example.

**Comment by tsujan** [comment] 2017-07-31 14:42
Although I can't reproduce this, it may somehow be related to https://github.com/lxde/pcmanfm-qt/issues/555.

Unfortunately, the job is still done in `libfm` and this may not be fixable until it's moved to `libfm-qt`.

**Comment by FrederikLauber** [comment] 2017-08-01 10:50
Some more information added.
If i select all files with CTRL+A in a folder, the number of files selected as well as their size is a factor of 4 to high.

**Comment by tsujan** [comment] 2017-08-01 11:27
> If i select all files with CTRL+A in a folder, the number of files selected as well as their size is a factor of 4 to high.

I didn't understand this sentence. Do you mean that if there are 100 files, then the number of selected files is 400 with `Ctrl+A`? There was a problem like this *only* for desktop but it's fixed now.

**Comment by FrederikLauber** [comment] 2017-08-01 11:35
Actually, it will show 500 files.
I attached a screenshot of the situation after CTRL+A.
My guess is, the deleting non existent files is actually a non existed files were passed to the routine somehow.
![strla](https://user-images.githubusercontent.com/17728264/28823491-21da2caa-76be-11e7-895c-d97209fb3278.png)

**Comment by tsujan** [comment] 2017-08-01 11:56
@FrederikLauber 
This is totally unusual! If you have Arch's pcmanfm-qt 0.11.3, it' very old (68 commits behind the latest git until now, which means it doesn't have many fixes or features). What @fulalas mentioned [above](https://github.com/lxde/pcmanfm-qt/issues/512#issuecomment-312261245) is a different problem.

**Comment by tsujan** [comment] 2017-08-01 11:58
@agaida Should we let the latest release be so behind the latest git?

**Comment by agaida** [comment] 2017-08-01 12:09
i have no problem doing so - really - there was much work at libfm-qt and pcmanfm-qt since the last release. For the next iterations we should plan different right from the beginning with two releases per year if possible. That was the intention of build tools and the latest changes in the CMakeLists.txt: Ease releases and point releases.

The pcman/libfm-qt situation is somewhat different. There was so much changes that it was not wise to release it earlier. And you might noticed that i'm in the "release preparation mode" for two weeks now. 

We said we will release faster - ETA was set to june/july +/- one month at the time we made the last point release. And i guess we will deliver soon.

**Comment by tsujan** [comment] 2017-08-01 12:17
@agaida Yes, libfm-qt and pcmanfm-qt usually change fast and I think that's good. IMHO, if there's no serious bug in the latest release, it could wait but apparently, there are bad bugs in it now, although I can't confirm that firsthand because I can never install the release -- probably, no LXQt member could ;)

**Comment by tsujan** [comment] 2017-08-01 12:21
On the other hand, there are some bugs, like https://github.com/lxde/pcmanfm-qt/issues/555, whose fix we might want to be in the next release. You'll have to make hard decisions and I don't have any suggestion here ;)

**Comment by agaida** [comment] 2017-08-01 12:48
thats easy: if there are a fix for it in the next two weeks - good, if not, also good. Might sound stubborn but i mentioned point releases :D  No joke, libfm-qt/pcmanfm-qt are release ready with or without this bug. And i would be glad if it will fixed before the release. I will also be glad toi trigger a point release for that if we can't make it in time - right, just for that bug.

Hmm - right now i'm in the prerelease mode, The release mode (or "full labrador mode") will look like this:
https://www.youtube.com/watch?v=iVypJWmV2wU&feature=youtu.be&t=223

**Comment by tsujan** [comment] 2017-08-01 12:56
OK, I'll fix this (as the title says, not the non-existent bug @FrederikLauber [described](https://github.com/lxde/pcmanfm-qt/issues/512#issuecomment-319345506)) in an hour -- not sure about a workaround for https://github.com/lxde/pcmanfm-qt/issues/555 -- but it'll need some tests.

**Comment by tsujan** [comment] 2017-08-01 13:26
Should be fixed by https://github.com/lxde/libfm-qt/pull/111.

**Comment by tsujan** [comment] 2017-08-01 13:39
@agaida BTW, your youtube link was wrong, unless you wanted me to see a concert in Amsterdam ;)

**Comment by agaida** [comment] 2017-08-01 15:34
the guitar player goes to full labrador mode at 3:50 or so

**Comment by tsujan** [comment] 2017-08-01 15:43
> the guitar player goes to full labrador mode at 3:50 or so

This time I was very careful no to spit on the monitor while laughing.

**Closed** 2017-09-14 19:25 UTC
