### ISSUE TITLE
Cannot untrash file foo: original path not known

### ISSUE THREAD

**Issue by ghost** [lxde/pcmanfm-qt#235] opened 2015-09-25 06:39 UTC
This message appears when I right click a file in trashcan and select Restore.
I think this happens when I trashed a file via another program.

Debian testing amd64

**Comment by pmattern** [comment] 2015-09-25 07:48
How did you install LXQt and which version are you running?

**Comment by fguzm** [comment] 2015-09-26 14:44
got it from siduction repository, version 090

**Comment by pmattern** [comment] 2015-09-26 23:27
I can confirm your findings on Siduction were they're affecting files moved to trash from within PCManFM-Qt as well, btw., but neither on Arch Linux running all LXQt components from recent VCS checkouts nor on Lubuntu using their LXQt PPA.
So this is a downstream issue and as such nothing that can be dealt with on this tracker. Hence closing.

Nevertheless one of the main downstream developers happens to be team member of LXQt, too. So
@agaida Ping. Any thoughts on this one?

**Comment by agaida** [comment] 2015-09-28 01:14
we will get current packages in the next few days. until they hit the repo i prefer to say nothing about this issue :)

**Comment by sleepy1** [comment] 2015-10-12 14:03
this happens to me to, but I'm on bridgelinux  lxde.

**Comment by agaida** [comment] 2015-10-12 16:24
linked in directories in home?

**Comment by farseenabdulsalam** [comment] 2015-10-13 14:49
I am running archlinux latest version, newly installed yesterday. I have installed pcmanfm , gvfs and udisks2 from the official repo. I'm experiencing the same issue.  And I have heard users of nautilus reporting the same issue in the #archlinux freenode channel. So, the issue seems to be within gvfs.

**Comment by pmattern** [comment] 2015-10-13 23:12
Unlike two weeks ago recent VCS checkouts of all LXQt components are now affected on up-to-date Arch Linux i686 or x86_64, too. Same thing with LXDE stable release on Arch Linux but still no problems with PCManFM-Qt from PPA ppa:lubuntu-dev/lubuntu-daily on Lubuntu 15.04, neither with KDE Plasma 5 / Dolphin on Arch Linux.
So indeed this may be an issue affecting an upstream component like GVFS itself or the interaction with LXQt.

@sleepy1 , @farseenabdulsalam 
Besides part of the LXDE project this tracker is dedicated to LXQt components only. LXDE issues are dealt with on https://sourceforge.net/projects/lxde and https://sourceforge.net/projects/pcmanfm respectively.

**Comment by Ilya87** [comment] 2016-03-20 15:47
Arch Linux x86-64, pcmanfm-qt, libfm, libfm-qt - git versions. No problem.

**Comment by tsujan** [comment] 2017-09-18 15:03
Not an issue after such a long time and so many changes.

**Closed by tsujan** 2017-09-18 15:03 UTC
