### ISSUE TITLE
Tab Drag-and-Drop

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#428] opened 2016-12-16 15:34 UTC
Tab detachment and DND is a feature that I think I can implement. Does anyone support this feature? Is it useful to you? I ask because I can live without it ;)

**Comment by tsujan** [comment] 2016-12-18 18:42
This is what I mean: [packaged video](https://www.dropbox.com/s/9scitbspke2ql3u/video.tar.gz?dl=0)

**Comment by agaida** [comment] 2016-12-18 19:45
detachable Tabs are nice - not that i would use them often, but from time to time - like detachable tabs in browsers, one don't miss them until they would be quite handy in some situations ...

To be true, i would like them, but i would like a second pane more for the beginning :D

**Comment by tsujan** [comment] 2016-12-18 19:58
> To be true, i would like them, but i would like a second pane more for the beginning

To me, tab DND was easy to implement because I'd done it in [FeatherPad](https://github.com/tsujan/FeatherPad) ;) I just wonder why none of the file managers that I've seen has it.

I never used a second pane in Dolphin or Nemo, so I don't understand why people like it. From what you said, I guess it's more usable that tab DND. Is it? If so, I'll start to think on it.

**Comment by agaida** [comment] 2016-12-18 20:31
to be true - i don't know - if i compare/sync directories i do it with beyond compare - so i really have not so much use cases for a second pane. but a lot of people seems to use dual pane in dolphin, don't know the reasons

**Comment by tsujan** [comment] 2016-12-18 20:47
>  i really have not so much use cases for a second pane but a lot of people seems to use dual pane in dolphin, don't know the reasons.

Then it may be just a matter of habit.

Anyway, since its logic is simple, I'll make a PR for tab DND after some tests and after that, I'll think on a second pane, although it can't be as easy to implement as DND is.

**Comment by agaida** [comment] 2016-12-18 20:59
ok - in that case i would like to suggest that we leave out DND for this release and push the button again when it is ready - to be honest, i would prefer this. The main reason for this point release is/should be introducing the build tools - and we should not put so much in it.

And i have no objections to push the big release button for the related packages mid of January again. What do you think?

**Comment by tsujan** [comment] 2016-12-18 21:12
> ok - in that case i would like to suggest that we leave out DND for this release and push the button again when it is ready 

@agaida, I don't have any objection at all. Frankly speaking, I don't see releases but the continuity of the work ;) Being "release-agnostic", it makes no difference to me which feature is in which release.

**Comment by agaida** [comment] 2016-12-18 21:15
less complex and overloaded things reduce the chance of regressions - or make it easy to find them - i'm not that release agnostic, but hey - i run sid, that will never be released and the latest git :D

**Comment by tsujan** [comment] 2016-12-18 21:18
I know you as the expert in that matter. You could ignore my opinion about releases -- I simply have none ;)

**Comment by tsujan** [comment] 2016-12-19 08:16
@agaida, it seems that you should wait a little more. When I was polishing tab DND I encountered and fixed two bugs in the new pathbar. Please see the new libfm-qt PRs!

**Comment by agaida** [comment] 2016-12-19 11:12
ok, nice, thank you

**Comment by stefonarch** [comment] 2016-12-22 19:57
> Anyway, since its logic is simple, I'll make a PR for tab DND after some tests and after that, I'll think on a second pane, although it can't be as easy to implement as DND is.

That would be very nice, I'm real missing dual pane/split view, specially while DND to folder view in side pane does still not work.

**Comment by tsujan** [comment] 2016-12-22 20:12
@stefonarch 
Don't you think that using split view is just a matter of habit? I mean, before I implemented tab DND I didn't need it but after that, I got addicted to it ;) and, maybe the same holds true for split view. And can't tab DND be used in the same scenarios (but in a different way, of course)?

Anyhow, unlike tab DND, split view isn't easy to implement. I'll work on it, hoping that it won't make pcmanfm-qt heavy.

**Comment by stefonarch** [comment] 2016-12-22 20:42
I always liked it for sorting files inside one window without fiddling around with more windows, pcmanfm has it this feature too. I don't see how to use dragging tabs for that, but I never saw this in real life ;)

**Comment by tsujan** [comment] 2016-12-22 21:13
> I don't see how to use dragging tabs for that...

See the video at https://github.com/lxde/pcmanfm-qt/issues/428#issuecomment-267838199 for how a window can be split into two (or more) winows and conversely, how two (or more) windows can be merged with each other quickly...

**Comment by MggMuggins** [comment] 2017-04-05 18:36
I'd support tab drag-n-drop so long as the feature is integrated well and is easy to use. Some browsers I've used have a hard time getting tabs to merge back into the main window. If integrated correctly, this would be a good feature.

**Comment by tsujan** [comment] 2017-04-05 18:42
It's don at https://github.com/lxde/pcmanfm-qt/pull/434 and I use it without problem since then.

**Comment by MggMuggins** [comment] 2017-04-05 18:43
Alright, any reason not to close this issue? On another note, do you guys have an up-to-date debian PPA? That would be super useful...

**Comment by tsujan** [comment] 2017-04-05 18:58
> Alright, any reason not to close this issue?

This PR isn't merged yet because of waiting for the changes I told about elsewhere.

> do you guys have an up-to-date debian PPA?

@agaida is our Debian guru. He had a repository but I can't answer your question with certainty.

**Comment by MggMuggins** [comment] 2017-04-05 19:58
Alright, I shot him an E-mail.

**Comment by agaida** [comment] 2017-04-06 22:34
@MggMuggins - debian has no such things like ppa's right now. But i have an inofficial repository that is build against sid at https://packages.4sid.eu - please be aware that i don't care if i break this repo from time to time - right now the parts that are in the lxqt-common transition  are built from their to merge branches.

So there can be temporary hickups - the good thing about the packages is: They are insane and bleeding edge and i use them on all my installations as  my daily driver.

**Comment by MggMuggins** [comment] 2017-04-07 01:43
Thanks for the response. I'll be aware of their instability, and won't complain when you guys break something. :P

**Closed** 2017-11-25 18:31 UTC
Labels: enhancement
