### ISSUE TITLE
Dragging to directory in sidebar with tree view not possibile

### ISSUE THREAD

**Issue by stefonarch** [lxde/pcmanfm-qt#224] opened 2015-09-04 16:45 UTC
There is no way to drag any file in a directory in the sidebar when "tree view" is chosen.

**Comment by pmattern** [comment] 2015-09-04 17:12
Problem is affecting places view as well and hence this is a duplicate of lxde/lxqt#446 if I'm not mistaken. (Directory Tree view mentioned in the course of the discussion only.)

**Comment by stefonarch** [comment] 2015-09-04 19:39
No problem with place view here.

**Comment by pmattern** [comment] 2015-09-05 11:56
> No problem with place view here.

To avoid misunderstanding please reproduce like this: open your home folder in places view
![pcmanfm-qt_d-and-d_places-vs-panes](https://cloud.githubusercontent.com/assets/9860801/9699109/aa7dd4fc-53d5-11e5-8e29-ad216c16534c.png)
and drag an object from the right pane into the folder representing the Desktop in the left pane. Does the object really show up on your desktop then?
Tbh I hardly believe it will as this is the very problem we've been discussing in lxde/lxqt#446 and that I've always been seeing ever since I started using LXQt here.

**Comment by stefonarch** [comment] 2015-09-05 13:21
Ok, same here, I was mislead by the green + icon which appears and did not finish.
In the tree view the red (-) icon (impossible) appears instead immediately.

**Comment by pmattern** [comment] 2015-09-05 14:42
> green + icon  [...] red (-) icon (impossible)

Cannot see any such icons here which may be due to different icon themes in use or whatever

Nevertheless I'm now convinced this should belong to lxde/lxqt#446. Feel free to add any relevant finding to that issue or let me know if you should disagree.

**Closed by pmattern** 2015-09-05 14:42 UTC

**Comment by stefonarch** [comment] 2015-09-05 18:32
The icons maybe are from my kde part, I'm running kwin and dolphin as default filemanager.
Closing because duplicate.
