### ISSUE TITLE
pcmanfm-qt executes desktop files without confirmation

### ISSUE THREAD

**Issue by cboxdoerfer** [lxde/pcmanfm-qt#449] opened 2017-01-31 17:03 UTC
How to reproduce:

1. Create a file called `malware.desktop`

2. Add the following content to it:

```
[Desktop Entry]
Name=CV.pdf
Exec=sh -c 'touch ~/MALWARE_WAS_HERE'
Terminal=false
Icon=x-office-document
Type=Application
Categories=Office
```

3. Make it executable

PCManFM (both GTK+ and Qt versions) displays the file like that:

![Screenshot](https://cloud.githubusercontent.com/assets/6108388/22475473/59c71df8-e7df-11e6-8292-4976dbbc695e.png)

Once the user opens the file the Exec entry is executed without any confirmation. By hiding the filename and therefore also the filename extension users can easily be tricked to execute arbitrary code when someone ships files like that in an archive which preserves execute permissions.

How to fix it:

Maybe by don't hiding the filename for .desktop files at all.

For reference, this bug also applies to other file managers:
https://bugzilla.gnome.org/show_bug.cgi?id=777991
https://github.com/mate-desktop/caja/issues/727
https://github.com/linuxmint/nemo/issues/1404

**Comment by tsujan** [comment] 2017-01-31 17:38
This is not a bug but the way desktop files are supposed to behave. What you want is not standard.

**Comment by arthurtiteica** [comment] 2017-01-31 18:13
You will probably have a flood coming into you. ;)

Maybe you should think some more on the issue before you make a decision.

Maybe it helps to see the bigger picture: https://www.reddit.com/r/linux/comments/5r6va0/how_to_easily_trick_file_manager_users_to_execute/

**Comment by rmcintosh** [comment] 2017-01-31 18:29
Why does it matter if what they want is "standard"? Just because something is a default or standard behavior doesn't mean that it should continue to exist when it's demonstrably dangerous for users of your software.

**Comment by tsujan** [comment] 2017-01-31 18:34
I agree that pcmanfm-qt should have an option to show a confirmation dialog on clicking desktop files (as it has for executables) and I AM WORKING ON IT.

If the title said, "pcmanfm-qt doesn't show confirmation dialog for desktop files", I wouldn't close it. A confirmaton dialog is enough to prevent such "dangers".

**Comment by rmcintosh** [comment] 2017-01-31 18:46
Fair enough - I think that's a fine solution. Your original comment read like you didn't think there was any problem at all but I agree that the title (hiding the name) and the underlying issue (executing .desktop files without confirmation) aren't the same.

**Comment by tsujan** [comment] 2017-01-31 19:04
@rmcintosh 
I saw this as a (minor) problem for a long time. Then I forgot it and this report reminded me of it.

My first comment was about showing filenames of desktop files -- something I always disliked in Dolphin. I admit that I also reacted to the demandingness of the report, as if showing filenames was a must.

**Comment by tsujan** [comment] 2017-01-31 20:24
OK, I succeeded in handling desktop files like executables. Most of the job should be done in libfm; libfm-qt just needs small changes and pcmanfm-qt needs none.

I'll make two PR's for this after some tests. The libfm PR may take a while to be merged -- if accepted at all -- but I'll try to be persuasive ;)

**Comment by tsujan** [comment] 2017-02-01 01:16
Done! The patches are [here](https://github.com/lxde/libfm/pull/21) and [here](https://github.com/lxde/libfm-qt/pull/62) (for those who want to test). The libfm-qt (second) patch is not essential.

**Comment by tsujan** [comment] 2017-07-23 17:03
I changed the label to "bug" because after comfortably using https://github.com/lxde/libfm/pull/21 for a long time, I see the hassle more clearly. https://github.com/lxde/libfm-qt/pull/62 is outdated but you could use https://github.com/lxde/libfm/pull/21 until the related functionality is implemented in `libfm-qt` and this issue is fixed there.

**Closed** 2017-11-06 10:54 UTC
Labels: bug

**Comment by dglent** [comment] 2018-05-31 15:43
Is it possible to have an option to disable the dialogue for the desktop files?
It is a little difficult to live with, every time i click on an desktop file entry on the Desktop to open an application i have to click a second time to launch it.

Actually there is no any security here because even if it was a malware i would click 'run' as i want to run the program.

**Comment by tsujan** [comment] 2018-05-31 15:47
@dglent With the latest git, Preferences → Behavior → Launch executable files without prompt
