### ISSUE TITLE
 View mode broken

### ISSUE THREAD

**Issue by acmondor** [lxde/pcmanfm-qt#409] opened 2016-11-04 16:36 UTC
I recently switch to switched LxQt-0.11.0 and pcmanfm-qt 0.11.1 and noticed an annoying issue with View mode. If I select something in the View menu which is different then my default settings (eg Show Hidden or Thumbnail View), when I change directory the setting goes back to its default value. In the previous version of pcmanfm-qt that setting would stay in effect until I changed it from the View menu or exited the application.

I stepped through the code with a debugger and confirmed the issue is very much related to the new "Preserve Settings for This Folder" feature's implementation.

I have created a small patch (see attached) which partially resolves this issue. I say partially because it works until the moment one changes to a directory with "Preserve Settings for This Folder" enabled. I typically do not have much of a need for the "Preserve Settings for This Folder" option, so I'm currently not motivated to address that aspect.

[acmondor-pcmanfm-qt-0.11.1.patch.txt](https://github.com/lxde/pcmanfm-qt/files/572062/acmondor-pcmanfm-qt-0.11.1.patch.txt)

**Comment by tsujan** [comment] 2016-11-04 16:48
Please see https://github.com/lxde/pcmanfm-qt/pull/391#issue-172981630 → 6

**Comment by tsujan** [comment] 2017-07-30 10:36
Hidden files issue is fixed. Going back to the view mode set in Preferences is by design, as mentioned above. Closing this.

**Closed by tsujan** 2017-07-30 10:36 UTC
