### ISSUE TITLE
Double MTP devices in sidepanel

### ISSUE THREAD

**Issue by equeim** [lxde/pcmanfm-qt#69] opened 2014-06-07 18:16 UTC
http://itmages.ru/image/view/1708540/70e59c35
When I click to "mtp", selection moves to "Xperia Acro S".

**Comment by PCMan** [comment] 2015-11-17 06:11
It's fixed in pcmanfm-qt now. This is caused by the change in newer gvfs/gio and the added g_mount_is_shadowed() API.

**Closed by PCMan** 2015-11-17 06:11 UTC
