### ISSUE TITLE
pcmanfm-qt: crashes when opening a folder with a specific jpeg in it

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/pcmanfm-qt#95] opened 2014-09-09 08:52 UTC
I have drilled down to a single jpg file causing pcmanfm to close, with an error message in dmesg.

`[ 5577.067837] loader[16696]: segfault at 30 ip 00007f781e9b5650 sp 00007f78037fccf8 error 4 in libQt5Gui.so.5.3.1[7f781e886000+513000]`

The jpg which causes this is the following (header-bg.jpg).

![header-bg](https://cloud.githubusercontent.com/assets/6639859/4198860/8e2d213e-37fe-11e4-8e37-9751139edc94.jpg)

**Comment by PCMan** [comment] 2015-01-21 07:51
Confirmed the bug. There lacks a NULL checking in libfm.
I'll work on this. Thanks!

**Comment by ArthurBorsboom** [comment] 2015-01-21 07:53
Awesome! This saves me removing that jpg everytime I extract and open an Oracle documentation package.

**Comment by PCMan** [comment] 2015-01-21 08:02
Fixed in the latest "libfm" in "git".

**Closed by PCMan** 2015-01-21 08:02 UTC

**Comment by ArthurBorsboom** [comment] 2015-01-21 08:08
Cool. I will be waiting until the v0.9 comes to AUR: https://aur.archlinux.org/packages/lxqt

Once that has happened, I will recheck all my open bug reports to verify their status.

Thanks PCMan!

**Comment by ArthurBorsboom** [comment] 2015-02-15 17:51
Issue still exists with

libfm 1.2.3
pcmanfm-qt 0.9.0

**Comment by PCMan** [comment] 2015-02-15 18:06
Yes, because there is no new release of libfm yet.
Version 1.2.3 does not contain the fix.

**Comment by ArthurBorsboom** [comment] 2015-02-15 18:30
Thanks for the clarification.
I will report back once the new libfm is released on my Arch system.
