### ISSUE TITLE
Pressing F4 does not focus xfce4-terminal

### ISSUE THREAD

**Issue by jimbo1qaz** [lxde/pcmanfm-qt#370] opened 2016-06-26 00:53 UTC
Ubuntu Studio 16.04 with Cinnamon and Lubuntu Daily PPA:

Annoying quirk I discovered:

If I set "terminal emulator" to xfce4-terminal, pressing F4 does not focus the terminal. gnome-terminal, qterminal, and xterm are unaffected. Is this a xfce4-terminal bug? Cinnamon bug?

**Comment by tsujan** [comment] 2016-06-26 01:06
You could answer your second question by trying to reproduce the problem under a DE other than Cinnamon ;) Please test!

**Comment by f2404** [comment] 2016-06-26 03:36
Can you also try xfce4-terminal from the git (it's been ported to gtk3)?

**Comment by pmattern** [comment] 2016-06-26 10:13
Cannot confirm your findings running latest VCS checkouts of all LXQt components and Xfce4 Terminal 0.6.3 on Arch Linux.
Xfce4 Terminal gets focussed much like all other terminal emulators, no matter whether it's launched by selecting "Open Terminal" from menu "Tools" or hitting `F4`. Same findings in an LXQt, Xfce or Openbox only session.
Maybe the problem is in Cinnamon or that PPA. Also, you may want to have a careful look of the focus settings of the window manager in use.

Anyway this doesn't look like a problem of PCManFM-Qt.
@tsujan Would you agree it can be closed as invalid?

**Comment by tsujan** [comment] 2016-06-26 11:51
> @tsujan Would you agree it can be closed as invalid?

Yes I do. Focusing is the job of WM. Closed.

**Closed by tsujan** 2016-06-26 11:51 UTC

**Comment by jimbo1qaz** [comment] 2016-06-26 19:02
Interestingly, I reverted to Ubuntu 16.04, and the bug *appears* to be
fixed. Is this a PPA or Git bug, or just random on my system?
