### ISSUE TITLE
segfault with invalid path in address bar

### ISSUE THREAD

**Issue by antis81** [lxde/pcmanfm-qt#200] opened 2015-07-22 08:04 UTC
Typing an invalid (not existing) path causes pcmanfm-qt to segfault (e.g. `/this/dir/does/not/exist`).

System:
```text
lubuntu     15.04 (64 bit)
pcmanfm-qt  0.9.0+bzr347+20
```

**Comment by luis-pereira** [comment] 2015-07-22 11:02
Can't reproduce it.
![screen-2015-07-22-03-20-42](https://cloud.githubusercontent.com/assets/62877/8823989/648dca7e-3026-11e5-8042-59b99e64d6a0.png)

**Comment by antis81** [comment] 2015-07-22 15:55
Hm ... actually pcanfm-qt just quits here - without message. Wasn't sure about a crash (apparently there's no crash report or coredump).

**Comment by luis-pereira** [comment] 2015-07-22 16:31
I'm using the latest libfm/libfm-qt/pcmanfm-qt. It works just fine

**Comment by pmattern** [comment] 2015-07-22 18:30
Seeing the same problem on up-to-date Lubuntu 15.04 with LXQt from ppa:lubuntu-dev/lubuntu-daily here but neither on Arch Linux running LXQt from latest Git checkout nor on Siduction running LXQt from their repos.
So it's pretty obviously a downstream issue, closing as such.
You may want to poke the PPA maintainers about it. After a while a GUI to submit a bug report cropped up here. Maybe you can use it.

**Closed by pmattern** 2015-07-22 18:30 UTC

**Comment by antis81** [comment] 2015-07-23 06:34
Thanks. This is a minor issue - I'll wait for next upstream release.

**Comment by q4a** [comment] 2015-08-18 02:25
reported to launchpad: https://bugs.launchpad.net/lubuntu-next/+bug/1485826
