### ISSUE TITLE
Delete key not working anymore for trashing files

### ISSUE THREAD

**Issue by stefonarch** [lxde/pcmanfm-qt#394] opened 2016-09-01 07:09 UTC
Hitting the delete key nothing happens anymore on selected files/folder in pcmanfm-qt windows. 
On the desktop it's still working. Latest git/arch packages. Not sure when this started, maybe after including per-folder-settings.

**Comment by tsujan** [comment] 2016-09-01 10:20
> Not sure when this started, maybe after including per-folder-settings.

It should be the cause. I still use my own method of per-folder-settings and `Delete` works here.

**Comment by stefonarch** [comment] 2016-09-01 14:22
Went back and compiled  with `git checkout 7c1220b20eec2c2dd33ff1469f92333103c3e98f` but issue sitll here, I see it on a fresh user too.

**Comment by tsujan** [comment] 2016-09-01 15:26
Here no problem with https://github.com/lxde/pcmanfm-qt/commit/d1d8e9fc7ef3b0d57599142e3c8ae495cb47dfcb either

**Comment by stefonarch** [comment] 2016-09-02 12:07
Just noticed that on my old laptop 32bit with LXQt and pcmanfm-qt packages from normal arch repos there is the same issue - at this point I guess it's arch-related.

**Comment by stefonarch** [comment] 2016-09-20 13:26
Solved on main PC after  upgrading arch packages, sorry for the noise.

**Comment by stefonarch** [comment] 2018-01-08 07:56
I see on a fresh install with arch 64bit official packages that  this issue is still present, at least in arch packages.

**Comment by tsujan** [comment] 2018-01-31 19:07
@stefonarch Localization and the lack of qt5-translations?

**Comment by agaida** [comment] 2018-01-31 19:19
I had similar problems in debian too a while ago - normally qttranslations5-l10n should™ be there, but one guy managed it to install the whole system without recommends - after that he complains about LXQt as not prime time ready - but thanks for bringing it up again, i for myself will add qttranslations to any l10n package as dependency, right now i only have it as a dependency for the lxqt metapackage.

**Comment by stefonarch** [comment] 2018-02-01 13:04
> Localization and the lack of qt5-translations?

Cannot tell anymore, the machine is with it's owner now.

**Comment by tsujan** [comment] 2018-02-01 13:13
> Cannot tell anymore, the machine is with it's owner now.

You mean you don't have LXQt on the computer you used right now?

**Comment by stefonarch** [comment] 2018-02-01 15:12
No, I have a 32bit arch and a 64bit git checkout - the machine I have set up for somebody else and it's not under my hands now anymore.

**Comment by tsujan** [comment] 2018-02-01 15:21
OK, to clear my busy mind, I close this ;) Reopen it if it happens *with* qt5-translations.

**Closed by tsujan** 2018-02-01 15:21 UTC
Labels: invalid

**Comment by stefonarch** [comment] 2019-02-13 18:18
And here again, fresh install and again same exact issue, solved by installing qt5-translations.

**Comment by agaida** [comment] 2019-02-13 18:39
hihihi - someone should update the dependencies - in debian i had qt5-translations as dependency for every translation package

**Comment by stefonarch** [comment] 2019-02-13 20:23
I have the list of installed packages saved, but I preferred to take advantage of the situation and installing only what I miss. Note to self: always backup /etc too...

**Comment by yan12125** [comment] 2019-02-14 01:54
> Of course, everything should be done manually on Arch because of its philosophy (which I admire but don't adhere to).

Here's a relevant request: https://bugs.archlinux.org/task/58182. The good news is that I'm now also an Arch Linux Trusted User now, co-maintaining almost all LXQt packages with jleclanche, and I plan to add qt5-translations to optdepends of the pcmanfm-qt package.

**Comment by tsujan** [comment] 2019-02-14 03:27
@yan12125 Great!

**Comment by tsujan** [comment] 2019-02-14 05:50
> I have the list of installed packages saved...

What I want to say is quite IRRELEVANT to this report but I can't help saying it whenever someone talks about (re-)installation: I've never seen a need to re-install any rolling distro in the 14 years I use Linux. Debian was on my desktop computer for 4 years and I transferred it to my laptop and used it for another 4-year period. I installed Manjaro on this laptop 2 years ago and I'll have it until the laptop won't be usable.

Hard-drive failure is the only good reason for re-installing a Linux distro, IMO (I think it was @stefonarch's reason). Other than that, re-installation never fixes a problem in Linux because, contrary to MS Windows, nothing is random in Linux.

I won't start a discussion about distro re-installation. I won't discuss either about how inefficient non-rolling distros line Ubuntu and Fedora are (they need re-installation most of the time).

**Comment by stefonarch** [comment] 2019-02-14 09:57
Agree 100%, usually changing the disk I copied over my system, it was also 14 years old or soo. Had just no recent copy. My system was on [one of those](https://www.qwant.com/?q=pcie%20ssd%2064gb&t=images), never again :) It started to blank screen and freeze, I thought it was the CPU/intel graphics first.

**Comment by agaida** [comment] 2019-02-14 15:37
erm - can't follow here, even ubuntu don't need re-installations if one know what one is doing (one might be surprised that this is possible with a so called open source software OS, but it is possible). Maybe an old relic from times when this open source software OS was Linux :P)

> Ubuntu is an open source software operating system that runs from the desktop, to the cloud, to all your internet connected things
https://ubuntu.com

**Comment by tsujan** [comment] 2019-02-14 15:52
> if one know what one is doing

I never re-installed a non-rolling distro either; started Linux with Fedora (Core 2?) and then went to Ubuntu. After each big update, I had to spend a lot of time (hours) to fix newly created problems. Debian saved me from those hassles. Even after 5-6 months, it could be updated almost smoothly.

**Comment by pablogzlezmora** [comment] 2022-06-18 04:02
I installed today _pcmanfm-qt_, with _qt5-translations_ on Arch. 

Delete key doesn't trash. :-(

**Comment by pablogzlezmora** [comment] 2022-06-18 12:52
I just installed _pcmanfm-qt_ on _Arch Linux_ with _i3-gaps_, and the _Delete_ key doesn't trash. The option _Delete_ in the _Edit_ menu doesn't show any shortcuts.

_Pacman_ preinstalled the package _qt5-translations_. Please, what step am I missing?

**Comment by tsujan** [comment] 2022-06-18 14:10
> The option Delete in the Edit menu doesn't show any shortcuts.

Most probably, `Del` is consumed by another app.

**Comment by pablogzlezmora** [comment] 2022-06-18 14:18
Thanks. I am going to check.

**Comment by stefonarch** [comment] 2022-06-18 14:44
> The option _Delete_ in the _Edit_ menu doesn't show any shortcuts.

Which language? Wrong translations can also disable shortcuts.

**Comment by pablogzlezmora** [comment] 2022-06-18 14:49
Spanish.

`$ locale -a`
```
C
C.UTF-8
es_VE.utf8
POSIX
```

**Comment by stefonarch** [comment] 2022-06-18 15:36
It's due to the translation: "Eliminar" doesn't work. In some languages translations work.
We'll fix it. If you have qt5translator installed remove the translation or change it to "Delete" and release the *_qm.file and save it to` /usr/share/pcmanfm-qt/translations/`
Thanks for reporting!

BTW I see that `&Copiar la dirección completa` has no shortcut too (should be ctrl+shift+c) because of `Ctrl+Mayús+C` we'll fix that too.

**Comment by stefonarch** [comment] 2022-06-18 15:41
It looks like the whole submenu for "create new" is disabled due to `Mayús`...
![schermata-18 giu 17:40-01](https://user-images.githubusercontent.com/10681413/174445967-70908634-080f-444f-a67b-9f627c95a08a.png)

**Comment by pablogzlezmora** [comment] 2022-06-18 15:54
Great, @stefonarch. Thanks.

I will try in a couple of hours.

**Comment by tsujan** [comment] 2022-06-18 17:09
So, it was a translation mistake again. I thought they were all corrected.

To find such mistakes, you could run the app without localization. If the shortcuts work, their translations should have a problem.

**Comment by stefonarch** [comment] 2022-06-18 17:10
> I will try in a couple of hours.

Done, for nearly all there were suggestions already in weblate: https://github.com/lxqt/pcmanfm-qt/pull/1604/files#diff-13c5de18ec0f7af0072b37f61b4c318ed52e906702b4b0a54598d181b4104eef

@tsujan Now it's clear: weblate does remove those narrow spaces, see the link ....

**Comment by stefonarch** [comment] 2022-06-18 17:18
> So, it was a translation mistake again. I thought they were all corrected.

I found some in italian now while going through this - it's hard to notice a shortcut which is NOT there ;)

And I would like to have a list of accepted translations for every language for Delete, Shift ecc. 
In spanish `Mayúsculas` for shift works apparently, in italian `Maiuscolo` doesn't.

**Comment by tsujan** [comment] 2022-06-18 17:23
> Now it's clear: weblate does remove those narrow spaces, see the link ....

I asked translators not to remove them, while all the time it was Weblate!

I guess there isn't a way for telling Weblate not to touch them.

**Comment by stefonarch** [comment] 2022-06-18 17:41
It's some time I suspected that and I didn't find anything useful.
Only way is to update translations before releasing - at least releases are ok.

**Comment by pablogzlezmora** [comment] 2022-06-18 23:33
I tried to compile the source, without success (I am a _pacman_/_AUR_ addict). I don't know to use (yet) the _qt-translations_ to get the new `*_qm.file`. So I have deleted the Spanish translation file. Next updating of the _AUR_ package, I could remove the package and reinstall it, getting the Spanish interface.

Thanks a lot.

**Comment by pablogzlezmora** [comment] 2022-06-19 01:47
I installed _pcmanfm-qt-git_ from AUR. It works very well with the Spanish translation: DEL key (_SUPRIMIR_): it sends to trash; CTRL+SHIFT+N: it creates a new folder; CTRL+ALT+N: it creates a new file.  The submenu for "Create new" is enabled.

Thanks a lot!!!!

**Comment by stefonarch** [comment] 2022-06-19 18:53
Not sure how this happened (automatically?), but there were 2 PR from weblate coauthored by me for `supr →suprimir` in LXimage-qt and lxqt-archiver, so the delete key will work there too now.
