### ISSUE TITLE
Allow to rename files within the 'Properties' dialog

### ISSUE THREAD

**Issue by goetzc** [lxde/pcmanfm-qt#324] opened 2016-03-07 01:30 UTC
This is like issue #319, but for the file name. There is actually an editable text filed, but upon clicking `OK`, the file is not renamed. Not sure if the current behavior it is a bug or a feature, hehe.

![pcmanfm-qt_file_prop](https://cloud.githubusercontent.com/assets/2220440/13558863/f0d51bf6-e3d9-11e5-9406-76c6ac65495e.png)

**Comment by palinek** [comment] 2016-03-07 12:33
Duplicate of lxde/lxqt#773... one should be closed.

**Comment by tsujan** [comment] 2016-03-07 16:02
I don't want to start a hot discussion about such a small thing here but if this feature is going to be added, it should **NOT** be by changing the lineedit string and then pressing `Enter` or `OK`; a new button will be needed.

If I made that properties dialog, I would use a selectable label instead of the lineedit, regardless of what other DEs do, because the string is info.

**Closed** 2016-03-28 09:27 UTC
