### ISSUE TITLE
Custom Actions issues

### ISSUE THREAD

**Issue by AcarBurak** [lxde/pcmanfm-qt#438] opened 2017-01-07 07:14 UTC
On an Arch/Fluxbox system with PCManFM-Qt 0.11.1

Issue 1:
A custom action with Folders key set to /home/… doesn't work; action doesn't appear in the context menu. Furthermore, right clicking on the / directory (on empty area inside the directory) crashes pcman. If I remove the Folder line from the action everything works fine, obviously, except for the action's intended purpose, to appear in only a specific folder. (pcmanfm-gtk3 has the same issue as well.) See below an example of such an action:

```
[Desktop Entry]
Type=Action
Name[en]=TermHere
Icon=utilities-terminal
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=inode/directory;
Folders=/home/burak/Desktop
Exec=xterm -e "cd %f; bash"
Name[en]=Default profile
```

Yet If I put `Folders=/run/media/…` everything works as expected without any of the above issues.

Issue 2:
I can't order my custom actions by a level-zero.directory as stated by http://www.nautilus-actions.org/?q=node/377.

Issue 3:
I can't group my actions under an actions menu, as you've already mentioned this in another issue.

**Comment by tsujan** [comment] 2017-01-07 10:15
This consists of 3 issues. Let's start with the third one. It's about a bug that's fixed months ago. Here, I have grouped actions without problem. For example, the following action groups two other actions into a submenu:
````
[Desktop Entry]
Type=Menu
Icon=application-x-bittorrent
Name=BitTorrent Actions
ItemsList = torrent-download;torrent-contents;
````
"torrent-download.desktop" and "torrent-contents.desktop" should exist in "~/.local/share/file-manager/actions", of course.

**Comment by AcarBurak** [comment] 2017-01-07 10:26
Thank you. Yes, I've exactly a similar menu file with .desktop extension in the same "~/.local/share/file-manager/actions", right?

**Comment by tsujan** [comment] 2017-01-07 10:32
Did you restart pcmanfm-qt from session setings → basic settings?

**Comment by AcarBurak** [comment] 2017-01-07 10:33
I quit/kill it, as I use Fluxbox session, not lxqt's.

**Comment by tsujan** [comment] 2017-01-07 10:36
> I quit/kill it, as I use Fluxbox session, not lxqt's.

It shouldn't make a difference. The problem in question is fixed in Sep 22, 2016 by https://github.com/lxde/libfm-qt/commit/149b4ec9b974fe6b5dcf5f4eb4f5d59bc04c74d0. Maybe your installed libfm-qt doesn't include that commit.

**Comment by AcarBurak** [comment] 2017-01-07 10:41
Its date in the Arch repo is 09.24 and the maintainer is Jerome Leclanche of lxqt though.

**Comment by tsujan** [comment] 2017-01-07 10:45
I think it doesn't include the commit.

Now I'm a little busy but I'll look into the second and first issues soon -- especially the first one seems important.

**Comment by AcarBurak** [comment] 2017-01-07 10:46
Thank you. Yes, the first is the real issue.

**Comment by tsujan** [comment] 2017-01-07 12:37
OK, I'm working on the second issue. I think the actions should appear according to the alphabetical order and based on their visible names. Do you agree? (The submenu actions -- which you don't have yet -- are ordered correctly, according to ItemsList)

**Comment by AcarBurak** [comment] 2017-01-07 12:46
Actions aren't listed alphabetically here, but I don't care for that. What I would like to get is the ability to order them myself, custom order which sould be possible by thet level-zero.directory mentioned above.

The reason is, I've got, for instance, two actions for images and I want them appear consecutively, yet they don't. Action Paramaters action is in the middle.

**Comment by tsujan** [comment] 2017-01-07 12:50
> Actions aren't listed alphabetically here

I know that. I just asked how they should be without a `level-zero.directory` file. The implementation of `level-zero.directory` will be the next step.

**Comment by tsujan** [comment] 2017-01-07 12:53
This is my plan:

(1) If there's no `level-zero.directory`, order should be alphabetical;
(2) All items in `level-zero.directory` should come first and according to the order specified in its `ItemsList`;
(3) Items that aren't in `ItemsList` should come after the items that are included in it in and in the alphabetical order.

Is this acceptable?

**Comment by AcarBurak** [comment] 2017-01-07 12:54
Perfectly.

**Comment by tsujan** [comment] 2017-01-07 12:57
OK! It may take some time but I'm working on it.

And thanks for the report! Although I often used custom actions, I didn't care about their order ;)

**Comment by AcarBurak** [comment] 2017-01-07 12:59
Thank you.

**Comment by tsujan** [comment] 2017-01-07 16:56
OK, I succeeded in implementing action order as explained above. I'll make a PR and add a link here after polishing/testing it for a few days. Then you could test it if you have git LXQt; otherwise you should wait until it's meged and Arch gets it.

**Comment by AcarBurak** [comment] 2017-01-07 17:01
All right, thanks.

**Comment by tsujan** [comment] 2017-07-27 08:26
Updated PR at https://github.com/lxde/libfm-qt/pull/108 for arranging custom actions.

**Comment by tsujan** [comment] 2017-07-29 22:27
Issue 2 is fixed. Issue 3 was fixed a long time ago.

I still have to see what "issue 1" is -- didn't think about it before.

**Comment by AcarBurak** [comment] 2017-07-30 09:22
Thank you.

**Comment by tsujan** [comment] 2017-12-15 10:14
Back to this. Now, custom actions are completely inside libfm-qt but the `Folders` key doesn't seem to be implemented yet.

**Comment by AcarBurak** [comment] 2017-12-15 12:48
All right; thanks.

**Comment by tsujan** [comment] 2017-12-19 12:11
Actually, I should thank you; I never used that key with custom actions and didn't know about it before you mentioned it ;) It's better to add it to pcmanfm-qt (libfm-qt, in fact).

**Comment by tsujan** [comment] 2017-12-19 12:17
For the record:

Yet another thing that may need a fix: without `level-zero.directory`, custom actions are ordered alphabetically but I still don't know that's the case with localization too. I should look into the code again but if you use localization, please test that (Name[..]=...).

**Comment by AcarBurak** [comment] 2017-12-19 12:43
You're wellcome.

No, I don't use localization.

**Comment by tsujan** [comment] 2017-12-19 14:52
Good news: The `Folders` key has already been implemented -- PCMan has been thorough -- but the code contains a small mistake, that I'll fix soon.

Also, the doc says, ".. . different implementations today widely consider that, for a directory point of view, having no selection is roughly the same that selecting the currently opened folder." If I'm not wrong, that means right-clicking (inside an empty place of) a folder, whose path is included in the value of `Folders`, should NOT show the custom action in question because the base directory should the *parent* folder. What do you think?

**Comment by AcarBurak** [comment] 2017-12-19 17:32
> Good news: The Folders key has already been implemented -- PCMan has been thorough -- but the code contains a small mistake, that I'll fix soon.

It has always been working outside /home, but you mean it works now in /home as well?

**Comment by tsujan** [comment] 2017-12-19 17:41
> It has always been working outside /home, but you mean it works now in /home as well?

With your sample custom action, it already works when you right click `/home/burak/Desktop/FOLDER1/FOLDER2`. After the issue is fixed, it'll work when you right click any `/home/burak/Desktop/FOLDER1`.

**Comment by AcarBurak** [comment] 2017-12-19 17:58
/home/burak/Desktop/FOLDER1/FOLDER2 doesn't work.
/home/burak/Desktop/FOLDER1 doesn't work.
/home/burak/Desktop doesn't work. And I want this to work for the above custom action for launching xterm in ~Desktop.

**Comment by tsujan** [comment] 2017-12-19 18:06
> /home/burak/Desktop/FOLDER1/FOLDER2 doesn't work.

It works here. Your pcmanfm-qt installation may be too old.

The fix is [here](https://github.com/lxde/libfm-qt/pull/147).

**Comment by tsujan** [comment] 2017-12-19 18:08
> /home/burak/Desktop doesn't work

It shouldn't -- even with the fix -- because `/home/burak/Desktop` is not INSIDE `/home/burak/Desktop`. But `/home/burak/Desktop/FOLDER` and `/home/burak/Desktop/FOLDER/...` should work with the fix.

**Comment by AcarBurak** [comment] 2017-12-19 18:13
I'm on Arch with pcman 0.12.0.

> It shouldn't -- even with the fix -- because /home/burak/Desktop is not INSIDE /home/burak/Desktop.

I kindly disagree.

**Comment by tsujan** [comment] 2017-12-19 18:26
> I'm on Arch with pcman 0.12.0.

Then, we may not talk about the same thing. I meant exactly with the sample you provided (just changed  `burak` to my user name) and on right-clicking the above-mentioned folders.

> I kindly disagree.

According to the doc, `Folders` is "a list of paths the current base directory must be in, in order the item be selected." The current base directory isn't *in* itself.

**Comment by AcarBurak** [comment] 2017-12-19 18:26
Yes, I've just updated my comment above, sorry for the noise.

**Comment by tsujan** [comment] 2017-12-19 18:29
> In other directories it works logically...

I didn't try that but if so, I'll be a little surprised :) although it shouldn't affect the fix.

**Comment by tsujan** [comment] 2017-12-19 19:11
On second thought, a directory is in its own *path* (although not in *itself* as a directory); so, it seems you're right: `/home/burak/Desktop` also needs to be included with your sample custom action. IMO, the doc isn't clear enough in this case but I'll modify the patch a little to include this case.

**Comment by AcarBurak** [comment] 2017-12-19 19:31
> the doc isn't clear enough
Agree.

In my sample replacing `Folders=` key with `Basenames=` solves my issue, but that DES-EMA thing seems a bit unecessarily complicated or unclear.

**Comment by tsujan** [comment] 2017-12-19 19:43
> In my sample replacing Folders= key with Basenames= solves my issue,..

IMO, the code should be a little easy-going. I found another case: when `Folders=/PATH/` (the last slash exists), the action never shows up. With a single commit, I'll also fix that in https://github.com/lxde/libfm-qt/pull/147. All cases will be covered so.

**Comment by AcarBurak** [comment] 2017-12-19 19:58
Very fine; thank you. Is pcman-qt based on DES-EMA in any way or is it just a convention it follows?

**Comment by tsujan** [comment] 2017-12-19 20:04
> Is pcman-qt based on DES-EMA in any way or is it just a convention it follows?

pcmanfm-qt supports DES-EMA as pcmanfm (gtk based) did; the `libfm` code is ported into c++11 by PCMan. That means pcmanfm-qt supports DES-EMA almost completely (and now, better than pcmanfm) -- "almost" because there are some missing cases but they'll be added when reported ;)

BTW, fixed the patch a few minutes ago.

**Closed** 2017-12-22 16:24 UTC
