### ISSUE TITLE
Cache seems messed

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#489] opened 2017-04-21 06:49 UTC
Follow the step by step:

Create a folder, let's say 'test'
Create a sub folder, let's say '1' (test/1)
Create a sub sub folder, let's say '2' (test/1/2)
Delete main folder 'test'
Now create 'test' again
Enter on it (you'll see '1' for a second, and then it'll disappear)
Create '1'.
Enter on it. You'll see '2' forever, but you didn't create it!

**Comment by palinek** [comment] 2017-04-21 06:59
What version of pcmanfm-qt are you using? I can't reproduce it here with the current master.

**Comment by fulalas** [comment] 2017-04-21 07:12
0.11.3

Can you at least see '1' disappearing quickly?

**Comment by palinek** [comment] 2017-04-21 07:17
> Can you at least see '1' disappearing quickly?

No.

But there were a bunch of huge changes in the master recently...

**Comment by fulalas** [comment] 2017-04-21 07:18
Right. Can you provide a build with Qt 5.7? I'm struggling to compile it :(

**Comment by palinek** [comment] 2017-04-21 07:22
What distro are you using?

For debian, there is a "snapshot" repository `deb http://lxqt.debian.net/debian lxqt-snapshots main`. In Arch you can use AUR.

**Comment by fulalas** [comment] 2017-04-21 07:53
I'm using Porteus distro, with a custom made LXQt. Maybe you can simply provide the binary, since pcmanfm-qt is just one file (or maybe also libfm). But at the moment I don't have Qt 5.8, just 5.7.

**Comment by palinek** [comment] 2017-04-21 08:22
> But at the moment I don't have Qt 5.8, just 5.7.

You don't need 5.8... you should be able to compile it with 5.7 just fine.

**Comment by fulalas** [comment] 2017-04-21 08:25
Yep, but Arch build was done with 5.8. So I don't have a build to test, and I'm having problems trying to compile it. :(

**Comment by yan12125** [comment] 2017-04-21 09:08
Did you get compile errors? Maybe we can see how to fix that.

**Comment by tsujan** [comment] 2017-04-21 10:19
This very similar to https://github.com/lxde/pcmanfm-qt/issues/460 and is related to libfm.

@fulalas 
Only the latest git version fixes the problem. However, I recommend you wait a month for its regressions to be fixed.

**Comment by fulalas** [comment] 2017-04-22 06:50
@yan12125, thanks. I'll try later and tell you which errors I'm getting so you can help me :)

@tsujan, nice to hear that. Do you know which regressions were made?

**Comment by fulalas** [comment] 2017-04-22 07:07
lxqt-build-tools built flawlessly. The problem starts with libfm-qt:
git clone ...
mkdir build
cd build
cmake ..
Then got this:
```
-- Found Fm: /usr/lib64/libfm.so (Required is at least version "1.2.0") 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find MenuCache (missing: MENUCACHE_INCLUDE_DIR) (Required is at
  least version "0.4.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/lxqt-build-tools/find-modules/FindMenuCache.cmake:84 (find_package_handle_standard_args)
  CMakeLists.txt:39 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by yan12125** [comment] 2017-04-22 09:13
> Could NOT find MenuCache (missing: MENUCACHE_INCLUDE_DIR) (Required is at least version "0.4.0")

You'll need menu-cache: https://github.com/lxde/menu-cache/

However, as @tsujan mentioned, the latest git of libfm-qt and pcmanfm-qt is not quite stable. Beware that there might be other bugs.

**Comment by tsujan** [comment] 2017-04-22 09:39
> Do you know which regressions were made?

Long story short, @PCMan started to make libfm-qt independent of libfm. It's a work in progress and will take some time to complete but the result will be a better file manager.

The problem you reported here isn't really related to cache and is fixed by the new code (automatically). However, new codes often need cleanup, which is mostly done in this case but not merged yet.

**Comment by fulalas** [comment] 2017-04-23 00:57
@yan12125, I see. Too much dependencies for my taste :(

@tsujan, this is great news! I'll wait for a stable build.

Thanks, guys!

**Comment by tsujan** [comment] 2017-04-23 05:10
OK. I close this because, first, it's a duplicate of https://github.com/lxde/pcmanfm-qt/issues/460 and, second, it's fixed.

**Closed by tsujan** 2017-04-23 05:10 UTC
